### ISSUE TITLE
[feature] scroll, not zoom

### ISSUE THREAD

**Issue by yuzhouwww** [AykutSarac/jsonvisio.com#10]
The experience of scrolling to zoom is very terrible

**Comment by AykutSarac** [comment]
I'm aware and working on it, I have decreased the zoom wheel step can you check it out and share me your feedback?

**Comment by yuzhouwww** [comment]
yeah, it feels much better now!

**Comment by thewh1teagle** [comment]
It again feels very uncomfortable. After you finish scrolling it pulls you in a certain direction, see in the video.
<video src="https://user-images.githubusercontent.com/61390950/187074259-438b6a0f-18fd-48a7-80ce-ae3a794ef53f.mp4"></video>

**Comment by AykutSarac** [comment]
> It again feels very uncomfortable. After you finish scrolling it pulls you in a certain direction, see in the video.
> 
>  simplescreenrecorder-2022-08-28_15.31.28.mp4

You're right, I see the problem here. I've increased the canvas padding now, currently in the pipeline. Could you try it in the editor after a few minutes and let me know your feedback?

**Comment by thewh1teagle** [comment]
> > It again feels very uncomfortable. After you finish scrolling it pulls you in a certain direction, see in the video.
> > simplescreenrecorder-2022-08-28_15.31.28.mp4
> 
> You're right, I see the problem here. I've increased the canvas padding now, currently in the pipeline. Could you try it in the editor after a few minutes and let me know your feedback?

It still feels the same. I would completely disable this auto positioning feature.
