### ISSUE TITLE
Import file feature loads graph for a brief period before reverting to previous content

### ISSUE THREAD

**Issue by Pustur** [AykutSarac/jsonvisio.com#18]
I tried to import several different json files with the "import file" feature.  
The graph renders the content for a brief period, but then it reverts back to what was displayed before.  
No errors are shown in the console.

https://user-images.githubusercontent.com/13663338/165147688-3dff7751-5579-43cd-9a24-bd8dc6045552.mov

Tested in:
- MacOS Monterey 12.3.1
- Chrome Version 100.0.4896.127 (arm64)

**Comment by AykutSarac** [comment]
Fixed with 017ce94b1ad79448e5083ff92191a2a8e34c7806, thanks for reporting!
