### ISSUE TITLE
[Feature] Collapse JSON Elements

### ISSUE THREAD

**Issue by andreisaikouski** [AykutSarac/jsonvisio.com#2]
Add ability to collapse JSON elements displayed in JSON view

**Comment by AykutSarac** [comment]
Thanks for your suggestion. I will definitely consider adding this.

**Comment by fredrikj31** [comment]
@AykutSarac Do you use a library to make the graph, or have you created the layout on your own?

I think it would be cool if you could click on the element, and it will collapse the clicked parents children.

**Comment by AykutSarac** [comment]
> @AykutSarac Do you use a library to make the graph, or have you created the layout on your own?
> 
> I think it would be cool if you could click on the element, and it will collapse the clicked parents children.

I've used the [reaflow](https://github.com/reaviz/reaflow) library. The library itself doesn't have collapse feature built-in though it does have delete node which removes all connectes nodes and edges of parent. Something similar could be implemented.

**Comment by fredrikj31** [comment]
Yeah maybe it could just be deleted. But I think that the delete functionality maybe causes a lot of performace issues. Would it not be better to just add a javascript `display: hidden;` and `box` to the child nodes?

**Comment by AykutSarac** [comment]
> Yeah maybe it could just be deleted. But I think that the delete functionality maybe causes a lot of performace issues. Would it not be better to just add a javascript `display: hidden;` and `box` to the child nodes?

Sounds good.

**Comment by AndrewLaganaro** [comment]
I support that, would be really useful

**Comment by oliverbutler** [comment]
We've got some legacy JSON objects with _huge_ values on some sections. 

Some of these can make the box 10 times longer than it is high.

I'm happy to try to solve this in a PR at some point, but possibly some kind of inline truncate, on the value level could be nice (That un-truncates if you click it)

![Screenshot 2022-09-20 at 14 36 44](https://user-images.githubusercontent.com/47489826/191272556-364a3bf8-ba31-4c06-88f0-4390386f03e8.png)
