### ISSUE TITLE
"Smart" rendering

### ISSUE THREAD

**Issue by Thiht** [AykutSarac/jsonvisio.com#29]
Given a JSON like this:

```js
{
  "values": [
    "foo-1",
    "foo-2",
    "foo-3",
    // ...
    "foo-1000"
  ]
}
```

The rendering becomes unreadable. Because this is an array of strings, maybe it's not necessary to represent 1 item = 1 node in this case? In general, arrays of primitive types could maybe be simplified to a single node with ellipsis, and details on click? This would drastically unclutter the rendering for specific JSON documents, and be way more useful to visualize the structure of these documents.

**Comment by AykutSarac** [comment]
If anyone would like to implement it I can review the PR.
