### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mykiwi** [AykutSarac/jsonvisio.com#41]
Hi,

I would like to generate (and download) the image of a big json, but the browser don't render it...
Here is what I saw in the console:

<details>
 <summary><code>❌ Uncaught Error: Maximum call stack size exceeded</code></summary>

  ```
errors.ts:22

  RangeError: Maximum call stack size exceeded
      at format.ts:247:14
      at Generator.next (<anonymous>)
      at b (cancellation.ts:97:1)
      at errors.ts:22:12
  ```
</details>
<details>
 <summary><code>⚠️ The number of foldable regions is limited to a maximum of 5000. Increase configuration option ['Folding Maximum Regions'](command:workbench.action.openSettings?["editor.foldingMaximumRegions"]) to enable more.</code></summary>

  ```
standaloneServices.ts:201 
  ```
</details>
<details>
 <summary><code>❌ Layout Error: RangeError: Maximum call stack size exceeded</code></summary>

  ```
25.9d8d1b145a1e1f12.js?__WB_REVISION__=9d8d1b145a1e1f12:1 

Layout Error: RangeError: Maximum call stack size exceeded
    at Dyn (72fdc299.13ac368d6056aded.js?__WB_REVISION__=13ac368d6056aded:1:657388)
    at Dyn (72fdc299.13ac368d6056aded.js?__WB_REVISION__=13ac368d6056aded:1:657614)
    at Dyn (72fdc299.13ac368d6056aded.js?__WB_REVISION__=13ac368d6056aded:1:657614)
    at Dyn (72fdc299.13ac368d6056aded.js?__WB_REVISION__=13ac368d6056aded:1:657614)
    at ...
  ```
</details>

Any idea how I could bypass this issue?
Thanks!

**Comment by yogananda-muthaiah** [comment]
I too have same issue with 5000 lines of JSON - cannot download a image..  Page goes down.

**Comment by victorbrambati** [comment]
In my desktop this working but the downloaded image is pixelated and freezing the page. For you generate a big json you need a mid-range video card. I don't see any reason for you download the image of a big json, the size of image will too big, I think it's better save the json and after paste on jsonvisio.com.

**Comment by AykutSarac** [comment]
I can import file ~11K lines of JSON, how big is your data?

**Comment by mykiwi** [comment]
In my case it was ~88k lines and ~3M characters

**Comment by AykutSarac** [comment]
Does it still occur?

**Comment by mykiwi** [comment]
There is no more errors but I still get the warning and nothing is shown
