### ISSUE TITLE
Can't open editor

### ISSUE THREAD

**Issue by BaoBaoss** [AykutSarac/jsonvisio.com#45]
I'm going to open the url: https://jsonvisio.com/editor ,But I can't open it. It's stuck. Below is the error message, I hope I can get help, thank you.
![image](https://user-images.githubusercontent.com/45710021/169729255-be6d0ccd-6be8-4429-b7d1-0405a3395db6.png)

**Comment by attitudefx7** [comment]
me too! 
![image](https://user-images.githubusercontent.com/39052856/169968165-806ba224-2649-4df5-95a8-08694496371e.png)

**Comment by BaoBaoss** [comment]
> me too! ![image](https://user-images.githubusercontent.com/39052856/169968165-806ba224-2649-4df5-95a8-08694496371e.png)

But I don't deploy locally, I open the official website

**Comment by God-wei** [comment]
![image](https://user-images.githubusercontent.com/37776021/170238123-5098dfee-9e76-47db-914d-30dd299a7f03.png)
me too!

**Comment by AykutSarac** [comment]
Hello, this is an issue with JSDelivr CDNs. https://github.com/jsdelivr/jsdelivr/issues/18397

**Comment by BaoBaoss** [comment]
> Hello, this is an issue with JSDelivr CDNs. [jsdelivr/jsdelivr#18397](https://github.com/jsdelivr/jsdelivr/issues/18397)

Okay, can we improve the code so that it works locally without DNS contamination? Like putting those files in a project or something like that. Of course, it is best to visit the official website normally.

**Comment by AykutSarac** [comment]
Hello,

Just pushed a fix, let me know if it will work for you.

**Comment by BaoBaoss** [comment]
> Hello,
> 
> Just pushed a fix, let me know if it will work for you.

Oh, yeah. It works for me. I can open the official website successfully. It's cool, thanks
