### ISSUE TITLE
[Feature] Search Feature

### ISSUE THREAD

**Issue by AykutSarac** [AykutSarac/jsonvisio.com#5]
Add a search feature lets you to search a specific node and focus to it on canvas.
Ref: Use zoomToNode feature of `react-zoom-pan-pich`

**Comment by AykutSarac** [comment]
Added **search node feature** (experimental) with [v1.3.0](https://github.com/AykutSarac/jsonvisio.com/releases/tag/v1.3.0).

**Comment by sk-surya** [comment]
Hi Aykut. How do I use this feature or have I not downloaded the right version?
I download the source code for v2.0.0 and built using docker.

**Comment by sk-surya** [comment]
Ah, got it. I was searching using 'Find' on left top. Didn't notice 'Search Nodes' on right top.
