### ISSUE TITLE
[BUG] Numbers are not rendered.

### ISSUE THREAD

**Issue by WORMSS** [AykutSarac/jsonvisio.com#6]
Numbers in arrays displays no value 
```json
[
  123,
  456
]
```
![image](https://user-images.githubusercontent.com/1384537/158913074-891cc41c-5324-4084-ab50-9099d4b26f82.png)

```json
{
  "stuff": [123, 456]
}
```
![image](https://user-images.githubusercontent.com/1384537/158913067-168ffe07-dc87-4007-8c36-714b0e687083.png)

**Comment by AykutSarac** [comment]
Should be fixed now with 0f94dc90466d1fc6a9ef5ff914c4600578d16714.

**Comment by WORMSS** [comment]
Confirmed.. good job @AykutSarac
