### ISSUE TITLE
Serviceworker not fetching external scripts

### ISSUE THREAD

**Issue by AykutSarac** [AykutSarac/jsonvisio.com#61]
All scripts are fetched before Serviceworker (from next-pwa package) registered, once the SW is registered and page refreshed some scripts fail to load such as googletagmanager and carbonads.

**Comment by XLpacman805** [comment]
Note: I'm getting redundant registered service workers, I think this is making the scripts not cache. The first time I ran and refreshed it cached and served from cache successfully.
