### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by clementdroillard** [AykutSarac/jsonvisio.com#64]
<img width="1274" alt="Capture d’écran 2022-06-22 à 09 40 11" src="https://user-images.githubusercontent.com/16818619/174972607-e23bfdcc-c9c6-443d-9c22-d0a2677daa93.png">

**Comment by AykutSarac** [comment]
Dupe of https://github.com/AykutSarac/jsonvisio.com/issues/67
