### ISSUE TITLE
feat: save as screenshot

### ISSUE THREAD

**Issue by fdemir** [AykutSarac/jsonvisio.com#66]
it would be great to have an option for saving as a screenshot. the app currently supports only exporting as JSON. if it's fit to the app I will be pleased to add this feature.

**Comment by AykutSarac** [comment]
This has been added yesterday. Check it out and let me know your feedbacks!

<img width="568" alt="image" src="https://user-images.githubusercontent.com/47941171/180603374-1de0e691-ffaf-496c-bd03-bbad2728e43a.png">
