### ISSUE TITLE
When running locally and opening editor - 404 Not Found error  

### ISSUE THREAD

**Issue by Zhambul** [AykutSarac/jsonvisio.com#67]
Steps to reproduce
1. Clone the project
2. docker build -t jsonvision .
3. docker run -p 8888:80 jsonvisio
4. go to localhost:8888
5. click 'Go to Editor'
6. **404 Not found error**

<img width="381" alt="image" src="https://user-images.githubusercontent.com/11275628/178661132-42ab14cb-953f-40d3-96b6-8c4fd50eda5f.png">

**Comment by caesartcs** [comment]
Same issue. Follow @Zhambul steps for reproduction

**Comment by AykutSarac** [comment]
Should be fixed with #91
