### ISSUE TITLE
Unable to find image 'jsonvisio:latest' locally

### ISSUE THREAD

**Issue by Jingle-Pan** [AykutSarac/jsonvisio.com#73]
Docker Installation prompt failed

**Comment by dariovjed** [comment]
Did you run the installation with root privileges? It worked for me that way.

**Comment by Jingle-Pan** [comment]
> Did you run the installation with root privileges? It worked for me that way.

It is root permission, but it cannot succeed. It is recommended to package it into hub.docker.com

**Comment by AykutSarac** [comment]
Should be fixed with #91
