### ISSUE TITLE
解析错误的bug

### ISSUE THREAD

**Issue by IsMoonset** [AykutSarac/jsonvisio.com#75]
包含的值为整数类型会改变内容

原始的：
{
"id": 8389765533338918725
}

解析后的：
{
"id": 8389765533338919000
}

工具很好用，希望支持多窗口，在对比两个json文件会用到

**Comment by AykutSarac** [comment]
Hello, can you please write it in English?

**Comment by AykutSarac** [comment]
> 包含的值为整数类型会改变内容
> 
> 原始的： { "id": 8389765533338918725 }
> 
> 解析后的： { "id": 8389765533338919000 }
> 
> 工具很好用，希望支持多窗口，在对比两个json文件会用到

It happens because it's not an integer.
