### ISSUE TITLE
http://localhost:8888/editor   404 Not Found

### ISSUE THREAD

**Issue by dariovjed** [AykutSarac/jsonvisio.com#77]
Hi,

I have executed the docker following the described steps, it starts but and when entering the editor the 404 error comes out. This is the docker log:

2022/08/03 13:26:28 [error] 37#37: *4 open() "/usr/share/nginx/html/editor" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /editor HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/"
172.17.0.1 - - [03/Aug/2022:13:26:28 +0000] "GET /editor HTTP/1.1" 404 153 "http://localhost:8888/" "Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0" "-"

**Comment by AykutSarac** [comment]
Should be fixed with #91
