### ISSUE TITLE
Tooltips not readable when displayed over an error message

### ISSUE THREAD

**Issue by pavelsaman** [AykutSarac/jsonvisio.com#78]
The "tooltips" are not easily readable when displayed over an error message:

![image](https://user-images.githubusercontent.com/24702416/183262797-1c8d9fd2-cf57-456b-bc19-59599c52d8fd.png)

**Comment by AykutSarac** [comment]
Should be fixed now with https://github.com/AykutSarac/jsonvisio.com/commit/ef8bec4c2a8310d467de6caf86b257515577e9b9.
