### ISSUE TITLE
"Expand Nodes" and "Shrink Nodes" look swapped

### ISSUE THREAD

**Issue by pavelsaman** [AykutSarac/jsonvisio.com#81]
The "Expand Nodes" tooltip and icon seem to be displayed when the nodes are in fact expanded:

![image](https://user-images.githubusercontent.com/24702416/183264730-a69e3413-0cb9-4c62-b528-7d065aae1858.png)

because when I click it, the nodes don't expand, but shrink:

![image](https://user-images.githubusercontent.com/24702416/183264743-c5beeb8b-0ec8-4e96-96a3-3792427c431d.png)

and the info message says:

![image](https://user-images.githubusercontent.com/24702416/183264801-7a84bfb7-b029-4369-a9a5-4e862615d3ec.png)

which also seems the other way around.

**Comment by AykutSarac** [comment]
Default width of the node might be misleading you, if you try with bigger object data you will notice it works intended.
