### ISSUE TITLE
Incorrect copy of arrays to clipboard 

### ISSUE THREAD

**Issue by pavelsaman** [AykutSarac/jsonvisio.com#83]
It seems that arrays cannot be correctly copied to a clipboard.

An array:

```json
[true]
```

when copied to a clipboard by double-click on the drawn box:

![image](https://user-images.githubusercontent.com/24702416/183265274-421cc91d-3064-4ef9-a06e-f298633ef7c0.png)

the clipboard will contain:

```
"true"
```

This might be desired in case that only the value should be copied. But the same doesn't go for objects:

```json
{"a":"1"}
```

will end up exactly that when copied to a clipboard. So in this case, the whole JSON was copied, not only the value. It seems inconsistent with the array example.

It also seems inconsistent with the claims the program makes. In case of the `[true]` array, it reports:

![image](https://user-images.githubusercontent.com/24702416/183265544-33c24873-982a-42ce-8767-19fc56cde999.png)

but `"true"` is not really an object when talking in JSON lingo.

**Comment by AykutSarac** [comment]
That's expected behaviour, special values like true, null or undefined are converted into string. Double click copies only the value inside of the node.
