### ISSUE TITLE
Hardcoded domain name

### ISSUE THREAD

**Issue by rlex** [AykutSarac/jsonvisio.com#86]
Hello! We deployed jsonvisio locally and people are quite happy with it, however i found that when you press share it still shows jsonvisio.com domain.

I wonder if it's possible to make that part configurable https://github.com/AykutSarac/jsonvisio.com/blob/87fba5e41046f25e83541be236e49921ff833e72/src/containers/Modals/ShareModal/index.tsx#L49-L50

IE with env variables at build time?

**Comment by AykutSarac** [comment]
Possible to do by changing package.json `homepage` value. Thanks for using JSON Visio!

**Comment by rlex** [comment]
That will require regular rebuilding of image, though. With env variable you can set it at runtime, which allows everyone to use official image.
